FROM zoobab/glar150
COPY blink /bin/blink
COPY stopblink /bin/stopblink
COPY high /bin/high
COPY low /bin/low
RUN chmod +x /bin/blink 
RUN chmod +x /bin/stopblink 
RUN chmod +x /bin/high
RUN chmod +x /bin/low
